spring:
  application:
    name: spring-6-rest-mvc
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:restdb
    user-name: sa
    password:
  h2:
    console.enabled: true
  #    hikari:
  #      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#        format_sql: true
#    show-sql: true

logging:
  level:
    guru:
      springframework:
        spring6restmvc: debug