spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    user-name: restadmin
    password: password
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
# show sql
        show-sql: true
# hibernate format sql
        format_sql: true
# highlight sql
        highlight_sql: true

#show bind values in sql
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace