spring:
  application:
    name: spring-6-rest-mvc
  h2:
    console:
      enabled: false
# DataSource config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    user-name: restadmin
    password: password
# Creating a DataSource Pool
    hikari:
      pool-name: RestDB-Pool-MySQL
      maximum-pool-size: 5
# Extra configuration for performance
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
# Configuring Hibernate and MySQL communication
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
# show sql
        show-sql: true
# hibernate format sql
        format_sql: true
# highlight sql
        highlight_sql: true
## Auto generation of scripts sql by hibernate
#      jakarta:
#        persistence:
#          schema-generation:
#            scripts:
#              action: drop-and-create
#              create-source: metadata
#              drop-target: src/scripts/drop-and-create.sql
#              create-target: src/scripts/drop-and-create.sql
#            create-database-schemas: true
#flyway configuration
  flyway:
    locations: "classpath:db/migration/mysql"
    enabled: true
#show bind values in sql
logging:
  level:
    org:hibernate.orm.jdbc.bind: trace
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace