spring:
# DataSource config
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/restdbh2
    user-name: sa
    password:
# Creating a DataSource Pool
    hikari:
      pool-name: RestDB-Pool-H2
      maximum-pool-size: 5
  h2:
    console:
      enabled: true
  # Configuring Hibernate and H2 communication
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
# show sql
        show-sql: true
# hibernate format sql
        format_sql: true
# highlight sql
        highlight_sql: true
#flyway configuration
  flyway:
    locations: "classpath:db/migration/h2"
    enabled: true
logging:
  level:
    guru:
      springframework:
        spring6restmvc: debug
