spring:
  profiles:
    active: localmysql
  application:
    name: spring-6-rest-mvc
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:restdb
    user-name: sa
    password:
  h2:
    console.enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#      jakarta:
#        persistence:
#          schema-generation:
#            scripts:
#              action: drop-and-create
#              create-source: metadata
##              drop-target: drop-and-create.sql
#              create-target: drop-and-create.sql
logging:
  level:
    guru:
      springframework:
        spring6restmvc: debug