spring:
  profiles:
    active: localmysql
  application:
    name: spring-6-rest-mvc
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:restdb
    user-name: sa
    password:
  h2:
    console.enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
logging:
  level:
    guru:
      springframework:
        spring6restmvc: debug